spring:
  application:
    name: queuesetu
  autoconfigure:
    exclude: com.queuesetu.boot.core.security.SecurityConfig

server:
  port: 8080

jwt:
  secret: o1b8X2Q9fN3uV7jKp4ZxHq2rYt6W0s9vABcDeFgHiJk=

application:
  security:
    jwt:
      refresh-token:
        expiration: 1000000

services:
  user:
    base-url: http://localhost:8085
  account:
    base-url: http://localhost:8086
  queue:
    base-url: http://localhost:8087
  booking:
    base-url: http://localhost:8089

logging:
  level:
    root: INFO
    com.queuesetu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
